---
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.js"
preMerge:
  pattern:
    - "./test/**/*.js"
preRun:
  command:
    - yarn install
    - yarn run build
postRun:
  command:
    - yarn --version
    - yarn --version
version: 1.0
