framework: mocha
preRun:
  command:
    - yarn install
    - yarn run build
preMerge:
  pattern:
    - "./test/src/**/*.js"
postMerge:
  pattern:
    - "./test/src/**/*.js"
postRun:
  command:
    - yarn --version
    - yarn --version
configFile: test/.mocharc.yml
version: 1.1
