---
framework: mocha
postMerge:
  pattern:
    - "./test/commands/*.js"
preMerge:
  pattern:
    - "./test/commands/*.js"
preRun:
  command:
    - yarn install
    - NODE_ENV=production yarn build
postRun:
  command:
    - yarn --version
configFile: "./test/.mocharc.yml"
version: 1.0
