---
framework: "mocha"
postMerge:
  pattern:
    - "test/**/*.js"
preMerge:
  pattern:
    - "test/**/*.js"
preRun:
  - yarn install
  - NODE_ENV=production yarn build
postRun:
  - yarn --version
configFile: "./test/.mocharc.yml"
version: 2.1
