---
framework: mocha
postMerge:
  pattern:
    - "./test/commands/*.js"
preMerge:
  pattern:
    - "./test/commands/*.js"
preRun:
  command:
    - yarn install
    - yarn run build
postRun:
  command:
    - yarn --version
configFile: "test/.mocharc.yml"
version: 1.0
