---
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.js"
preMerge:
  pattern:
    - "./test/**/*.js"
preRun:
  command:
    - yarn install
    - yarn run prepare
postRun:
  command:
    - yarn --version
configFile: "./test/.mocharc.yml"
version: 1.0
